<?php

namespace Database\Seeders;

use App\Models\Pendaftar;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DemoSantriPutriSeeder extends Seeder
{
    /** Membuat akun santri demo beserta data pendaftaran yang saling terhubung. */
    public function run(): void
    {
        // Hanya santri yang diterima, aktif, atau alumni yang membutuhkan akun login.
        foreach ($this->santriPutri() as $data) {
            $needsAccount = in_array($data['status'], ['aktif', 'diterima', 'alumni'], true);
            $passwordAwal = $data['nomor_induk_santri'];
            $user = null;

            if ($needsAccount) {
                $user = User::updateOrCreate(
                    ['email' => $data['email']],
                    [
                        'name' => $data['nama'],
                        'nomor_induk_santri' => $data['nomor_induk_santri'],
                        'password' => Hash::make($passwordAwal),
                        'role' => 'santri',
                    ],
                );
            }

            Pendaftar::updateOrCreate(
                ['email' => $data['email']],
                array_merge($data, [
                    'password_awal' => $needsAccount ? $passwordAwal : null,
                ]),
            );
        }
    }

    /** Menyediakan fixture santri putri yang mewakili variasi status aplikasi. */
    private function santriPutri(): array
    {
        return [
            [
                'nama' => 'Zahra Aulia Rahma',
                'email' => 'demo.putri01@darulfurqon.test',
                'nomor_induk_santri' => '2026001',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Kudus',
                'tgl_lahir' => '2012-01-12',
                'alamat' => 'Desa Jati Kulon, Kudus',
                'asal_sekolah' => 'MI Al Falah Kudus',
                'nama_ayah' => 'Ahmad Fauzi',
                'pekerjaan_ayah' => 'Wiraswasta',
                'nama_ibu' => 'Nur Khasanah',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'wa_wali' => '081300000001',
                'wa_santri' => '081300000001',
                'kemampuan_membaca_alquran' => 'Lancar',
                'jumlah_hafalan' => 'Juz 30',
                'riwayat_penyakit' => '-',
                'motivasi_masuk_pondok' => 'Ingin memperkuat hafalan Al-Quran dan belajar mandiri.',
                'status' => 'menunggu',
                'status_pembayaran' => 'menunggu_verifikasi',
                'tanggal_upload_pembayaran' => now()->subDays(8),
                'catatan' => 'Data demo calon santri putri menunggu verifikasi.',
            ],
            [
                'nama' => 'Naila Safira Hidayah',
                'email' => 'demo.putri02@darulfurqon.test',
                'nomor_induk_santri' => '2026002',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Jepara',
                'tgl_lahir' => '2012-03-04',
                'alamat' => 'Desa Tahunan, Jepara',
                'asal_sekolah' => 'MI Miftahul Huda Jepara',
                'nama_ayah' => 'Slamet Riyadi',
                'pekerjaan_ayah' => 'Petani',
                'nama_ibu' => 'Siti Aminah',
                'pekerjaan_ibu' => 'Pedagang',
                'wa_wali' => '081300000002',
                'wa_santri' => '081300000002',
                'kemampuan_membaca_alquran' => 'Cukup Lancar',
                'jumlah_hafalan' => '15 Surat Pendek',
                'riwayat_penyakit' => '-',
                'motivasi_masuk_pondok' => 'Ingin belajar tahfidz dengan jadwal yang terarah.',
                'status' => 'menunggu',
                'status_pembayaran' => 'menunggu_verifikasi',
                'tanggal_upload_pembayaran' => now()->subDays(7),
                'catatan' => 'Data demo calon santri putri menunggu verifikasi.',
            ],
            [
                'nama' => 'Aisyah Putri Lestari',
                'email' => 'demo.putri03@darulfurqon.test',
                'nomor_induk_santri' => '2026003',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Pati',
                'tgl_lahir' => '2011-11-21',
                'alamat' => 'Desa Margorejo, Pati',
                'asal_sekolah' => 'SD Islam Terpadu Pati',
                'nama_ayah' => 'Budi Santoso',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'nama_ibu' => 'Fitri Handayani',
                'pekerjaan_ibu' => 'Guru',
                'wa_wali' => '081300000003',
                'wa_santri' => '081300000003',
                'kemampuan_membaca_alquran' => 'Lancar',
                'jumlah_hafalan' => '1 Juz',
                'riwayat_penyakit' => '-',
                'motivasi_masuk_pondok' => 'Ingin menjadi hafidzah dan memperdalam ilmu agama.',
                'status' => 'menunggu',
                'status_pembayaran' => 'belum_upload',
                'tanggal_upload_pembayaran' => null,
                'catatan' => 'Data demo calon santri putri belum upload bukti pembayaran.',
            ],
            [
                'nama' => 'Khanza Nur Fadilah',
                'email' => 'demo.putri04@darulfurqon.test',
                'nomor_induk_santri' => '2026004',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Demak',
                'tgl_lahir' => '2012-05-19',
                'alamat' => 'Desa Karangawen, Demak',
                'asal_sekolah' => 'MI Darussalam Demak',
                'nama_ayah' => 'Heri Prasetyo',
                'pekerjaan_ayah' => 'Sopir',
                'nama_ibu' => 'Yuli Astuti',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'wa_wali' => '081300000004',
                'wa_santri' => '081300000004',
                'kemampuan_membaca_alquran' => 'Cukup Lancar',
                'jumlah_hafalan' => 'Juz 30',
                'riwayat_penyakit' => 'Alergi debu ringan',
                'motivasi_masuk_pondok' => 'Ingin membiasakan diri dengan lingkungan pesantren.',
                'status' => 'menunggu',
                'status_pembayaran' => 'menunggu_verifikasi',
                'tanggal_upload_pembayaran' => now()->subDays(5),
                'catatan' => 'Data demo calon santri putri menunggu verifikasi.',
            ],
            [
                'nama' => 'Salsabila Nur Azizah',
                'email' => 'demo.putri05@darulfurqon.test',
                'nomor_induk_santri' => '2026005',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Semarang',
                'tgl_lahir' => '2011-09-08',
                'alamat' => 'Tembalang, Semarang',
                'asal_sekolah' => 'SDIT Bina Insani Semarang',
                'nama_ayah' => 'Agus Setiawan',
                'pekerjaan_ayah' => 'Pegawai Negeri',
                'nama_ibu' => 'Rina Marlina',
                'pekerjaan_ibu' => 'Perawat',
                'wa_wali' => '081300000005',
                'wa_santri' => '081300000005',
                'kemampuan_membaca_alquran' => 'Lancar',
                'jumlah_hafalan' => '2 Juz',
                'riwayat_penyakit' => '-',
                'motivasi_masuk_pondok' => 'Ingin melanjutkan hafalan dengan bimbingan ustadzah.',
                'status' => 'menunggu',
                'status_pembayaran' => 'belum_upload',
                'tanggal_upload_pembayaran' => null,
                'catatan' => 'Data demo calon santri putri belum upload bukti pembayaran.',
            ],
            [
                'nama' => 'Rania Mutiara Salma',
                'email' => 'demo.putri06@darulfurqon.test',
                'nomor_induk_santri' => '2026006',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Rembang',
                'tgl_lahir' => '2012-07-17',
                'alamat' => 'Lasem, Rembang',
                'asal_sekolah' => 'MI Riyadlotut Thalabah Rembang',
                'nama_ayah' => 'Miftahudin',
                'pekerjaan_ayah' => 'Nelayan',
                'nama_ibu' => 'Lailatul Fitriyah',
                'pekerjaan_ibu' => 'Pedagang',
                'wa_wali' => '081300000006',
                'wa_santri' => '081300000006',
                'kemampuan_membaca_alquran' => 'Masih Dibimbing',
                'jumlah_hafalan' => '10 Surat Pendek',
                'riwayat_penyakit' => '-',
                'motivasi_masuk_pondok' => 'Ingin memperbaiki bacaan Al-Quran dan menambah hafalan.',
                'status' => 'perlu_perbaikan',
                'status_pembayaran' => 'menunggu_verifikasi',
                'tanggal_upload_pembayaran' => now()->subDays(4),
                'catatan' => 'Data demo perlu perbaikan alamat wali.',
            ],
            [
                'nama' => 'Hafshah Latifa Qonita',
                'email' => 'demo.putri07@darulfurqon.test',
                'nomor_induk_santri' => '2026007',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Grobogan',
                'tgl_lahir' => '2012-02-23',
                'alamat' => 'Purwodadi, Grobogan',
                'asal_sekolah' => 'MI Al Hikmah Grobogan',
                'nama_ayah' => 'Khoirul Anam',
                'pekerjaan_ayah' => 'Buruh',
                'nama_ibu' => 'Maimunah',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'wa_wali' => '081300000007',
                'wa_santri' => '081300000007',
                'kemampuan_membaca_alquran' => 'Cukup Lancar',
                'jumlah_hafalan' => 'Juz 30',
                'riwayat_penyakit' => '-',
                'motivasi_masuk_pondok' => 'Ingin belajar disiplin dan memperdalam tajwid.',
                'status' => 'perlu_perbaikan',
                'status_pembayaran' => 'ditolak',
                'tanggal_upload_pembayaran' => now()->subDays(3),
                'catatan' => 'Data demo perlu upload ulang bukti pembayaran.',
            ],
            [
                'nama' => 'Maryam Zahira Annisa',
                'email' => 'demo.putri08@darulfurqon.test',
                'nomor_induk_santri' => '2026008',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Blora',
                'tgl_lahir' => '2011-12-02',
                'alamat' => 'Cepu, Blora',
                'asal_sekolah' => 'SD Islam Al Madina Blora',
                'nama_ayah' => 'Teguh Wibowo',
                'pekerjaan_ayah' => 'Pedagang',
                'nama_ibu' => 'Dewi Lestari',
                'pekerjaan_ibu' => 'Penjahit',
                'wa_wali' => '081300000008',
                'wa_santri' => '081300000008',
                'kemampuan_membaca_alquran' => 'Lancar',
                'jumlah_hafalan' => '1 Juz',
                'riwayat_penyakit' => '-',
                'motivasi_masuk_pondok' => 'Ingin menjaga hafalan dalam lingkungan yang baik.',
                'status' => 'perlu_perbaikan',
                'status_pembayaran' => 'menunggu_verifikasi',
                'tanggal_upload_pembayaran' => now()->subDays(2),
                'catatan' => 'Data demo perlu melengkapi nomor WA wali.',
            ],
            [
                'nama' => 'Santri Demo Putri',
                'email' => 'santri@darulfurqon.test',
                'nomor_induk_santri' => '2026009',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Kudus',
                'tgl_lahir' => '2011-01-15',
                'alamat' => 'Alamat demo santri putri aktif',
                'asal_sekolah' => 'MI Demo Putri',
                'nama_ayah' => 'Ayah Demo',
                'pekerjaan_ayah' => 'Wiraswasta',
                'nama_ibu' => 'Ibu Demo',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'wa_wali' => '081300000009',
                'wa_santri' => '081300000009',
                'kemampuan_membaca_alquran' => 'Lancar',
                'jumlah_hafalan' => '1 Juz',
                'riwayat_penyakit' => '-',
                'motivasi_masuk_pondok' => 'Akun demo untuk pengujian login santri putri.',
                'status' => 'aktif',
                'status_pembayaran' => 'terverifikasi',
                'tanggal_upload_pembayaran' => now()->subDays(20),
                'catatan' => 'Akun demo untuk pengujian login santri.',
            ],
            [
                'nama' => 'Farah Nurul Izzah',
                'email' => 'demo.putri10@darulfurqon.test',
                'nomor_induk_santri' => '2026010',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Kudus',
                'tgl_lahir' => '2011-04-28',
                'alamat' => 'Bae, Kudus',
                'asal_sekolah' => 'MI Qudsiyyah Kudus',
                'nama_ayah' => 'Rohman Hakim',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'nama_ibu' => 'Istiqomah',
                'pekerjaan_ibu' => 'Guru Ngaji',
                'wa_wali' => '081300000010',
                'wa_santri' => '081300000010',
                'kemampuan_membaca_alquran' => 'Lancar',
                'jumlah_hafalan' => '2 Juz',
                'riwayat_penyakit' => '-',
                'motivasi_masuk_pondok' => 'Ingin memperbaiki murajaah dan menambah hafalan.',
                'status' => 'aktif',
                'status_pembayaran' => 'terverifikasi',
                'tanggal_upload_pembayaran' => now()->subDays(21),
                'catatan' => 'Data demo santri aktif putri.',
            ],
            [
                'nama' => 'Humaira Adiba Tsania',
                'email' => 'demo.putri11@darulfurqon.test',
                'nomor_induk_santri' => '2026011',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Jepara',
                'tgl_lahir' => '2011-06-14',
                'alamat' => 'Mayong, Jepara',
                'asal_sekolah' => 'MI Matholiul Huda Jepara',
                'nama_ayah' => 'Arif Mustofa',
                'pekerjaan_ayah' => 'Pengrajin',
                'nama_ibu' => 'Kurniawati',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'wa_wali' => '081300000011',
                'wa_santri' => '081300000011',
                'kemampuan_membaca_alquran' => 'Lancar',
                'jumlah_hafalan' => 'Juz 30 dan Juz 29',
                'riwayat_penyakit' => '-',
                'motivasi_masuk_pondok' => 'Ingin belajar kitab dasar dan tahfidz.',
                'status' => 'aktif',
                'status_pembayaran' => 'terverifikasi',
                'tanggal_upload_pembayaran' => now()->subDays(22),
                'catatan' => 'Data demo santri aktif putri.',
            ],
            [
                'nama' => 'Ruqayyah Salma Khairunnisa',
                'email' => 'demo.putri12@darulfurqon.test',
                'nomor_induk_santri' => '2026012',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Pati',
                'tgl_lahir' => '2010-10-31',
                'alamat' => 'Tayu, Pati',
                'asal_sekolah' => 'MI Tarbiyatul Banin Pati',
                'nama_ayah' => 'Joko Pramono',
                'pekerjaan_ayah' => 'Petani',
                'nama_ibu' => 'Sri Wahyuni',
                'pekerjaan_ibu' => 'Pedagang',
                'wa_wali' => '081300000012',
                'wa_santri' => '081300000012',
                'kemampuan_membaca_alquran' => 'Lancar',
                'jumlah_hafalan' => '3 Juz',
                'riwayat_penyakit' => '-',
                'motivasi_masuk_pondok' => 'Ingin menjaga hafalan dan belajar hidup sederhana.',
                'status' => 'aktif',
                'status_pembayaran' => 'terverifikasi',
                'tanggal_upload_pembayaran' => now()->subDays(23),
                'catatan' => 'Data demo santri aktif putri.',
            ],
            [
                'nama' => 'Dhiya Amani Fauziah',
                'email' => 'demo.putri13@darulfurqon.test',
                'nomor_induk_santri' => '2026013',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Demak',
                'tgl_lahir' => '2011-08-09',
                'alamat' => 'Mranggen, Demak',
                'asal_sekolah' => 'SD Islam Sultan Fatah Demak',
                'nama_ayah' => 'Mansur Hidayat',
                'pekerjaan_ayah' => 'Pedagang',
                'nama_ibu' => 'Rahmawati',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'wa_wali' => '081300000013',
                'wa_santri' => '081300000013',
                'kemampuan_membaca_alquran' => 'Lancar',
                'jumlah_hafalan' => '2 Juz',
                'riwayat_penyakit' => '-',
                'motivasi_masuk_pondok' => 'Ingin fokus menghafal Al-Quran.',
                'status' => 'aktif',
                'status_pembayaran' => 'terverifikasi',
                'tanggal_upload_pembayaran' => now()->subDays(24),
                'catatan' => 'Data demo santri aktif putri.',
            ],
            [
                'nama' => 'Fatimah Az Zahra Maulida',
                'email' => 'demo.putri14@darulfurqon.test',
                'nomor_induk_santri' => '2026014',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Semarang',
                'tgl_lahir' => '2010-02-11',
                'alamat' => 'Pedurungan, Semarang',
                'asal_sekolah' => 'SD Islam Hidayatullah Semarang',
                'nama_ayah' => 'Dedi Kurniawan',
                'pekerjaan_ayah' => 'Pegawai Negeri',
                'nama_ibu' => 'Husnul Khotimah',
                'pekerjaan_ibu' => 'Bidan',
                'wa_wali' => '081300000014',
                'wa_santri' => '081300000014',
                'kemampuan_membaca_alquran' => 'Lancar',
                'jumlah_hafalan' => '4 Juz',
                'riwayat_penyakit' => '-',
                'motivasi_masuk_pondok' => 'Ingin memperkuat akhlak dan hafalan.',
                'status' => 'aktif',
                'status_pembayaran' => 'terverifikasi',
                'tanggal_upload_pembayaran' => now()->subDays(25),
                'catatan' => 'Data demo santri aktif putri.',
            ],
            [
                'nama' => 'Lathifa Zahwa Kirana',
                'email' => 'demo.putri15@darulfurqon.test',
                'nomor_induk_santri' => '2026015',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Rembang',
                'tgl_lahir' => '2010-12-18',
                'alamat' => 'Pamotan, Rembang',
                'asal_sekolah' => 'MI An Nashriyah Rembang',
                'nama_ayah' => 'Hasan Basri',
                'pekerjaan_ayah' => 'Guru',
                'nama_ibu' => 'Umi Kulsum',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'wa_wali' => '081300000015',
                'wa_santri' => '081300000015',
                'kemampuan_membaca_alquran' => 'Lancar',
                'jumlah_hafalan' => '3 Juz',
                'riwayat_penyakit' => '-',
                'motivasi_masuk_pondok' => 'Ingin belajar istiqamah dalam murajaah.',
                'status' => 'aktif',
                'status_pembayaran' => 'terverifikasi',
                'tanggal_upload_pembayaran' => now()->subDays(26),
                'catatan' => 'Data demo santri aktif putri.',
            ],
            [
                'nama' => 'Syifa Nur Annisa',
                'email' => 'demo.putri16@darulfurqon.test',
                'nomor_induk_santri' => '2026016',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Grobogan',
                'tgl_lahir' => '2011-03-27',
                'alamat' => 'Godong, Grobogan',
                'asal_sekolah' => 'MI Yatpi Grobogan',
                'nama_ayah' => 'Syaiful Bahri',
                'pekerjaan_ayah' => 'Wiraswasta',
                'nama_ibu' => 'Erna Wati',
                'pekerjaan_ibu' => 'Penjahit',
                'wa_wali' => '081300000016',
                'wa_santri' => '081300000016',
                'kemampuan_membaca_alquran' => 'Lancar',
                'jumlah_hafalan' => '2 Juz',
                'riwayat_penyakit' => '-',
                'motivasi_masuk_pondok' => 'Ingin menghafal Al-Quran sampai selesai.',
                'status' => 'aktif',
                'status_pembayaran' => 'terverifikasi',
                'tanggal_upload_pembayaran' => now()->subDays(27),
                'catatan' => 'Data demo santri aktif putri.',
            ],
            [
                'nama' => 'Tsabita Hanun Mardhiyah',
                'email' => 'demo.putri17@darulfurqon.test',
                'nomor_induk_santri' => '2026017',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Blora',
                'tgl_lahir' => '2010-07-05',
                'alamat' => 'Randublatung, Blora',
                'asal_sekolah' => 'MI Al Islam Blora',
                'nama_ayah' => 'Mulyono',
                'pekerjaan_ayah' => 'Petani',
                'nama_ibu' => 'Sulastri',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'wa_wali' => '081300000017',
                'wa_santri' => '081300000017',
                'kemampuan_membaca_alquran' => 'Lancar',
                'jumlah_hafalan' => '5 Juz',
                'riwayat_penyakit' => '-',
                'motivasi_masuk_pondok' => 'Ingin menjaga hafalan bersama teman-teman santri.',
                'status' => 'aktif',
                'status_pembayaran' => 'terverifikasi',
                'tanggal_upload_pembayaran' => now()->subDays(28),
                'catatan' => 'Data demo santri aktif putri.',
            ],
            [
                'nama' => 'Azka Nabila Wardani',
                'email' => 'demo.putri18@darulfurqon.test',
                'nomor_induk_santri' => '2026018',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Kudus',
                'tgl_lahir' => '2008-09-13',
                'alamat' => 'Gebog, Kudus',
                'asal_sekolah' => 'MTs NU Banat Kudus',
                'nama_ayah' => 'Ridwan Saleh',
                'pekerjaan_ayah' => 'Pedagang',
                'nama_ibu' => 'Mahmudah',
                'pekerjaan_ibu' => 'Guru',
                'wa_wali' => '081300000018',
                'wa_santri' => '081300000018',
                'kemampuan_membaca_alquran' => 'Lancar',
                'jumlah_hafalan' => '10 Juz',
                'riwayat_penyakit' => '-',
                'motivasi_masuk_pondok' => 'Ingin melanjutkan hafalan dan mengabdi setelah lulus.',
                'status' => 'alumni',
                'status_pembayaran' => 'terverifikasi',
                'tanggal_upload_pembayaran' => now()->subDays(500),
                'catatan' => 'Data demo alumni putri.',
            ],
            [
                'nama' => 'Shafira Rahmi Amalia',
                'email' => 'demo.putri19@darulfurqon.test',
                'nomor_induk_santri' => '2026019',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Jepara',
                'tgl_lahir' => '2008-04-22',
                'alamat' => 'Keling, Jepara',
                'asal_sekolah' => 'MTs Matholiul Falah Jepara',
                'nama_ayah' => 'Saiful Anwar',
                'pekerjaan_ayah' => 'Nelayan',
                'nama_ibu' => 'Nurhayati',
                'pekerjaan_ibu' => 'Pedagang',
                'wa_wali' => '081300000019',
                'wa_santri' => '081300000019',
                'kemampuan_membaca_alquran' => 'Lancar',
                'jumlah_hafalan' => '12 Juz',
                'riwayat_penyakit' => '-',
                'motivasi_masuk_pondok' => 'Ingin menjadi hafidzah dan mengajar anak-anak.',
                'status' => 'alumni',
                'status_pembayaran' => 'terverifikasi',
                'tanggal_upload_pembayaran' => now()->subDays(520),
                'catatan' => 'Data demo alumni putri.',
            ],
            [
                'nama' => 'Zulfa Kamila Sakinah',
                'email' => 'demo.putri20@darulfurqon.test',
                'nomor_induk_santri' => '2026020',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Pati',
                'tgl_lahir' => '2007-12-30',
                'alamat' => 'Juwana, Pati',
                'asal_sekolah' => 'MTs Salafiyah Pati',
                'nama_ayah' => 'Abdul Wahid',
                'pekerjaan_ayah' => 'Wiraswasta',
                'nama_ibu' => 'Kholifah',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'wa_wali' => '081300000020',
                'wa_santri' => '081300000020',
                'kemampuan_membaca_alquran' => 'Lancar',
                'jumlah_hafalan' => '15 Juz',
                'riwayat_penyakit' => '-',
                'motivasi_masuk_pondok' => 'Ingin menyelesaikan hafalan dan memperdalam ilmu agama.',
                'status' => 'alumni',
                'status_pembayaran' => 'terverifikasi',
                'tanggal_upload_pembayaran' => now()->subDays(540),
                'catatan' => 'Data demo alumni putri.',
            ],
        ];
    }
}
